FROM python:3.10.6

RUN apt update && apt install -y --no-install-recommends 
RUN useradd -ms /bin/bash python
RUN pip install pdm    

USER python

WORKDIR /home/python/app
COPY . .

ENV MY_PYTHON_PACKAGES=/home/python/app/__pypackages__/3.10
ENV PYTHONPATH=${PYTHONPATH}/home/python/app/src
ENV PATH $PATH:${MY_PYTHON_PACKAGES}/bin
ENV PYTHONDONTWRITEBYTECODE=1

RUN echo 'eval "$(pdm --pep582)"' >> ~/.bashrc

EXPOSE 9000
